#!/bin/sh

# /etc/php/php.ini
# uncomment and set cgi.fix_pathinfo to 0
sed -i -e 's/\;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/' /etc/php/php.ini

# /etc/php/php-fpm.conf
sed -i -e "s/;pid = run\/php-fpm.pid/pid = \/run\/php-fpm\/php-fpm.pid/;
s/user = nobody/user = nginx/;
s/group = nobody/group = nginx/;
s/;listen.owner = nobody/listen.owner = nginx/;
s/;listen.group = nobody/listen.group = nginx/;
s/;listen.mode = 0660/listen.mode = 0660/;" /etc/php/php-fpm.conf
